import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    // <html lang="en" data-arp="" className="geist_a715...">
    //   <body className="min-h-full flex flex-col" cz-shortcut-listen="true">
    //     {children}
    //   </body>
    // </html>
    // =======================
    // <div className="h-screen flex">
    //   {/* Left */}
    //   <div className="w-1/6 bg-gray-900">L</div>
    //   {/* Right */}
    //   <div className="w-5/6 bg-gray-100">R</div>
    // </div>

    // =======================
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <div className="h-screen flex">
          {/* Left Sidebar */}
          <div className="w-64 bg-gray-900 text-white p-4">L</div>

          {/* Right Content */}
          <div className="flex-1 bg-gray-100 p-4">{children}</div>
        </div>
      </body>
    </html>
  );
}
